SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER personal_finance_system CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao excluir usuário: ' || SQLERRM);
END;
/

CREATE USER personal_finance_system IDENTIFIED BY finance123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO personal_finance_system;

GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE SEQUENCE,
    CREATE VIEW,
    CREATE PROCEDURE
TO personal_finance_system;
